sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t waleedmoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true waleedmoo/docker-react npm run test
